name: Publish code
on:
  schedule:
    - cron: '0 9-11 * * *' # every day between 9-11am UTC time

jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: YOUR_USERNAME/YOUR_REPO_NAME
          ref: main
      - name: Publish code
        run: |
          cd path/to/your/code
          echo "$(cat $(ls * | shuf -n 1))" > random-code.txt
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add random-code.txt
          git commit -m "Add random code for today"
          git push
